name: Conditionals Demo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'   # Runs only on push (not PR)

    steps:
      - name: Step runs only on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This runs only on main branch"

      - name: Step that fails intentionally
        run: exit 1

      - name: Run only if previous step failed
        if: failure()
        run: echo "Previous step failed, so this runs"

      - name: Continue even if error occurs
        continue-on-error: true
        run: |
       #   echo "This step will fail but workflow continues"
          exit 1

      - name: This still runs because of continue-on-error
        run: echo "Workflow did not stop"
