name: Hello Script

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Greet hello
        run: echo "Hello from git workflow"

      - name: Print date and time
        run: date

      - name: Print branch name
        run: echo "Branch: ${{ github.ref_name }}"

      - name: List all the files
        run: ls -la

      - name: Print runner operating system
        run: echo "Runner OS: $RUNNER_OS"
