name: Run Shell Script

on: push

jobs:
  test-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x .github/workflows/script.sh

      - name: Run script
        run: .github/workflows/script.sh

