name: Smart Trigger - Paths

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - 'src/**'
      - 'app/**'

jobs:
  run-on-code-change:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered because src/ or app/ changed"
