name: Use Action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run action
        id: greet
        uses: ./.github/actions/setup-and-greet
        with:
          name: Umesh

      - name: Check output
        run: echo "Greeted: ${{ steps.greet.outputs.greeted }}"
